{
 "title": "Application Performance ",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Error rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(django_http_responses_total_by_status_total{status=\"200\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "latency(p95)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, rate(django_http_requests_latency_seconds_by_view_method_bucket[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "\"Request Rate(RPS)\"",
   "type": "timeseries",
   "description": "\"shows total incoming speed per second\"",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(django_http_requests_total_by_method_total[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Active Requests(in-progress)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(django_http_requests_total_by_method_total[1m])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}