{
 "title": "🎯 CELERY DASHBOARD",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "🧩 Group 1: Worker Health & Processes",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "🧩 Panel 1 — Worker Health (Heartbeat)",
   "type": "stat",
   "description": "Meaning:\nIf 1 → Worker alive\nIf 0 → Worker dead",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "celery_worker_up", "legendFormat": "{{hostname}}" }
   ]
  },
  {
   "title": "Panel 2 — Active  workers",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "Count" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "celery_active_worker_count #Time-series (per queue) — line chart (Shows current value and history per queue_name)\n",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(celery_active_worker_count)#Single-value aggregated (total across all queues) — stat panel (Shows total active workers across queues)\n",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by(queue_name) (celery_active_worker_count{queue_name=\"celery\"})",
     "legendFormat": "__auto"
    },
    { "expr": "celery_active_process_count", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Panel 3 → Active Processes per Worker",
   "type": "stat",
   "description": "Monitor how many Celery worker processes are currently running per queue or worker.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "Count" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "celery_active_process_count#Per queue\n",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(celery_active_process_count)\n#Aggregated total",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by (queue_name) (celery_active_process_count)\n#Per queue summary",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "“Worker Utilization (%)”",
   "type": "gauge",
   "description": "Track whether Celery has free capacity.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "celery_active_worker_count / celery_active_process_count * 100\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "🧩 Group 2: Task Load & Performance",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true
  },
  {
   "title": "Panel 4 – Task Throughput (Tasks per second)",
   "type": "stat",
   "description": "tracks worker throughput over time",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "rate(celery_task_succeeded_total[1m])\n#A — Successful tasks per second\n",
     "legendFormat": "Success Rate"
    },
    {
     "expr": "rate(celery_task_failed_total[1m])\n",
     "legendFormat": "Failure ({{exception}})"
    },
    {
     "expr": "rate(celery_task_succeeded_total[1m]) + rate(celery_task_failed_total[1m])\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Current Active Tasks",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(celery_worker_tasks_active)",
     "legendFormat": "Active Tasks"
    }
   ]
  },
  {
   "title": "Panel 5: Average Task Execution Time",
   "type": "stat",
   "description": "Shows task runtime trends (avg, P90, P95)",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(celery_task_runtime_sum[15m])) / (sum(rate(celery_task_runtime_sum[15m])))",
     "legendFormat": "Avg"
    },
    {
     "expr": "histogram_quantile(0.9, sum by(le) (rate(celery_task_runtime_bucket[15m])))",
     "legendFormat": "p90"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(celery_task_runtime_bucket[15m])))",
     "legendFormat": "p95"
    },
    {
     "expr": "sum by(name) (rate(celery_task_runtime_sum[15m])) / (sum by(name) (rate(celery_task_runtime_count[15m])))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.99, sum by(le) (rate(celery_task_runtime_bucket[5m])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "🧩 Group 3: Queue Health",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 },
   "collapsed": true
  },
  {
   "title": "Queue Utilization (Workload Pressure)",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "(\n  sum(celery_queue_length{queue_name=\"celery\", instance=\"celery-exporter:9808\"})\n  /\n  sum(celery_active_worker_count{instance=\"celery-exporter:9808\"})\n) * 100\n\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "⚙️ Panel 6 — “Queue Backlog (Pending Tasks)”",
   "type": "stat",
   "description": "This panel shows how many tasks are currently waiting in the broker queue (i.e., not yet picked up by a worker).This is crucial because it tells you instantly whether workers are keeping up or falling behind.\n\nIf this value spikes or stays high, it means:\n\nThe workers can’t process fast enough.\n\nThere’s a bottleneck or task storm coming.\n\nIt’s time to scale out (add more workers or processes).",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "celery_queue_length#(If you have multiple queues, use sum(celery_queue_length) by (queue_name).)\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "🧩 Group 4: Failures & Reliability",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 },
   "collapsed": true
  },
  {
   "title": "Panel 7 — Task Failures & Retries Trend",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "ops/s" } },
   "targets": [
    {
     "expr": "sum(rate(celery_task_failed_total[5m])) by (exception)\n\n",
     "legendFormat": "{{exception}}"
    },
    {
     "expr": "sum by(name) (rate(celery_task_retried_total[5m]))",
     "legendFormat": "Retried{{name}}"
    },
    {
     "expr": "sum(rate(celery_task_failed_total[5m])) + sum(rate(celery_task_retried_total[5m]))\n",
     "legendFormat": "failed+retried"
    }
   ]
  },
  {
   "title": "Task Failure Rate(%)",
   "type": "stat",
   "description": "give the clear health snapshot",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "( rate(celery_task_failed_total[5m]) / ( rate(celery_task_succeeded_total[5m]) + rate(celery_task_failed_total[5m]) ) ) * 100\n",
     "legendFormat": "__auto"
    },
    { "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Retries, Rejections, Revokes",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(celery_task_retried_total[5m]))",
     "legendFormat": "Average Runtime"
    },
    {
     "expr": "sum(increase(celery_task_rejected_total[5m]))\n",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(increase(celery_task_revoked_total[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Task Failures by Exception Type",
   "type": "timeseries",
   "description": "task failures grouped by exception type ",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "ops/s" } },
   "targets": [
    {
     "expr": "sum by (exception) (rate(celery_task_failed_total[5m]))",
     "legendFormat": "{{exception}}"
    }
   ]
  }
 ]
}