{
 "title": "Database Observability Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Resource & Health Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true
  },
  {
   "title": "DB Process CPU (% of one core)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(process_cpu_seconds_total{job=\"postgres_exporter\"}[5m]))*100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "DB Process RSS (MB)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{job=\"postgres_exporter\"} / 1024 / 1024",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Active DB Connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(pg_stat_activity_count{datname=\"obsdb\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "DB Disk IO (blocks/sec)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(pg_stat_database_blks_read{datname=\"obsdb\"}[5m])",
     "legendFormat": "Reads/sec"
    },
    {
     "expr": "\nrate(pg_stat_database_blks_read{datname=\"obsdb\"}[5m])",
     "legendFormat": "Writes/sec"
    }
   ]
  },
  { "title": "Performance Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Query Throughput (QPS)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(pg_stat_database_xact_commit{datname=\"obsdb\"}[1m]) + rate(pg_stat_database_xact_rollback{datname=\"obsdb\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Avg Query Latency (ms)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg by (datname)(pg_stat_statements_mean_time_seconds{datname=\"obsdb\"})*1000\n\n",
     "legendFormat": "Avg Query({{dat name}})"
    }
   ]
  },
  {
   "title": "Slow Queries (>1s)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(datname)(rate(pg_stat_statements_calls[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Buffer Cache Hit Ratio (%)",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(rate(pg_stat_database_blks_hit{datname=\"obsdb\"}[5m]) / (rate(pg_stat_database_blks_hit{datname=\"obsdb\"}[5m]) + rate(pg_stat_database_blks_read{datname=\"obsdb\"}[5m]))) * 100\n\n"
    }
   ]
  }
 ]
}